### ISSUE TITLE
'videosnap: Bad CPU type in executable' on Intel Core Duo 1.66ghz / 10.5.8

### ISSUE THREAD

**Issue by allankh** [matthutchinson/videosnap#10] opened 2015-10-06 02:52 UTC
Hello. I've been using this happily on newer hardware, but I just inherited an older 2006 era Mac Mini running at 1.66ghz and on Mac OS X.5.8 (Leopard). As per the readme, this _should_ be supported? The thing is, I get "videosnap: Bad CPU type in executable" when running videosnap -l

Any ideas?

Thank you for the awesome utility :)

**Comment by matthutchinson** [comment] 2015-10-06 10:18
Thanks for reporting, I'll take a look and why this might be and get back to you.  It is possible I had the wrong build settings selected last time I compiled.

**Comment by matthutchinson** [comment] 2015-10-06 13:58
Out of interest, what CPU are you running on that Mac, is it an Intel or PowerPC chip?

Select '_About this Mac_' - from the top left apple menu, and look for the Processor details.  While I do support Leopard, VideoSnap doesn't support PowerPC based architectures.

**Comment by allankh** [comment] 2015-10-06 18:43
![capricorn-screen-about](https://cloud.githubusercontent.com/assets/691483/10318646/4cacad1e-6c1f-11e5-9f6f-69efeca4ea65.png)

It's a second-gen Intel chip :)

**Comment by matthutchinson** [comment] 2015-10-11 13:48
So the real problem here is that VideoSnap (right now) requires ARC (automatic reference counting).  This is available in 64 bit CPUs for OSX 10.5+ but not 32 bit, unless you have OSX 10.6+ (see the Xcode build output below)..

<img width="542" alt="screen shot 2015-10-11 at 14 34 46" src="https://cloud.githubusercontent.com/assets/2095/10417051/68e1e480-7026-11e5-9b13-2ff6f32fce7d.png">

So this is why the currently binary is built for 64bit Architectures only (your Mac Mini Intel CPU is 32 bit).  

So what i've done is create a [new branch](https://github.com/matthutchinson/videosnap/tree/cross-platform-compatible) with a test release that has a universal (32/64bit) binary, but targeting 10.6+. 

https://github.com/matthutchinson/videosnap/tree/cross-platform-compatible

**Can you try it on your Mac Mini** (with 10.5, Leopard) and see if you have any issues :question:  
If you do you will probably have to update to 10.6 (Snow Leopard) for VideoSnap to work for you.

A better fix would be to fix VideoSnap to work without ARC, which unfortunately I do not have time to do right now (PR's are welcome!).

**Comment by allankh** [comment] 2015-10-13 02:26
Unfortunately I get the same error on the recompiled binary on 10.5.

I've got a couple of GBs of RAM on the way from Amazon, and as soon as that gets here and I can pop it in, I'll upgrade to Snow Leopard and let you know if it works there.

I'm not much for Objective C, but I'll take a peek about the ARC maybe submit a PR, but I kinda doubt it :)

Thank you so very much for looking at this! It's already saved me a bunch of time.

Cheers!

**Comment by allankh** [comment] 2015-10-21 04:37
2GB of RAM installed, system upgraded to Snow Leopard, but the same error :(

![screen shot 2015-10-20 at 9 38 17 pm](https://cloud.githubusercontent.com/assets/691483/10627789/b99c65d2-7772-11e5-96e6-70d4c8836b6f.png)

**Comment by matthutchinson** [comment] 2015-10-27 15:30
Ok, a couple more things to try;

I've learned that Snow Leopard on Intel Core Duo, will boot into 32bit mode by default.  
Can you run this and tell me what it gives you?

    uname -m

For 64bit you'd see `x86_64`, and 32bit would show `i386`.  If you see `i386` you can try the advice [here](https://support.apple.com/en-us/HT3773) to boot your mac with a 64 bit kernel.  However your mac mini [may not support](https://support.apple.com/en-us/HT3770) this.  But worth a shot.

I tried to reproduce the problem and installed 10.6.8 on a virtual machine, but since it uses a virtual CPU that matches my own hardware, everything works since its 64bit.  And I don't have any 32bit CPUs to test this out with.

**Comment by allankh** [comment] 2015-11-03 04:28
Sorry for the delayed response.

My machine doesn't do 64bit, apparently :(

Thank you for putting so much effort into this, but I think my system is just too old, probably by a matter of months.

**Comment by matthutchinson** [comment] 2015-11-10 18:05
Hmm, i don't want to be beaten by this, so i'm not closing the issue just yet..  I have an idea to try another approach.  Will update here if I succeed.

**Comment by matthutchinson** [comment] 2015-11-19 21:25
Ok, so after trying a bunch of things I've had to call time on this one...  I tried building a universal binary, to include 32/64 bit but in doing so had to remove [ARC](https://en.wikipedia.org/wiki/Automatic_Reference_Counting) which caused a bunch of issues leading to memory leak errors.  

I tried an ARC bridge header but had no luck with that either. So basically I was unable to get the binary to run on my 10.6.8 OSX virtual machine (on 32bit Intel CPU).  The whole thing felt a bit like this;

![t0xhtgj](https://cloud.githubusercontent.com/assets/2095/11284862/019c0e0c-8f04-11e5-965a-e4f2355400e9.gif)

I've decided to change the README to indicate that I only support 10.7+ (and hence x86_64 CPU's only)
For older machines and OSX i'd suggest you try the (very old) command line video capture tool [wacaw](http://webcam-tools.sourceforge.net/).

**Closed by matthutchinson** 2015-11-19 21:25 UTC
Labels: bug

**Comment by allankh** [comment] 2015-11-23 21:43
I cannot properly express my gratitude for your efforts :) keep up the great work!

I did explored wacaw a bit (before I found videosnap even), and it works, but it necessitates transcoding pre-publishing, which complicates matters and seems to result in quality loss. I don't mind adding a bit of extra code house ffmpeg, but it's not the same. Videosnap is where it's at.
